stages:
  - build
  - test

build-app:
  image: docker:git
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE backend/

services:
    - mysql:5.7

variables:
  MYSQL_DATABASE: "home_tools"
  MYSQL_ROOT_PASSWORD: "home_password"
  MYSQL_ROOT_USERNAME: "root"
  MYSQL_HOST: "mysql"

test-app:
  image: python:3.7
  stage: test
  before_script:
    - cd backend
    - pip install -r requirements.txt
    - pip install pytest coverage
    - python manage.py makemigrations api
    - python manage.py migrate
  script:
    - coverage run manage.py test
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  when: manual
