stages:
  - test

services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: "home_tools"
    MYSQL_ROOT_PASSWORD: "home_password"
    MYSQL_HOST: "db"

test-app:
  image: python:3.7
  stage: test
  before_script:
    - cd backend
    - python manage.py makemigrations api
  script:
    - pip install -r requirements.txt
    - pip install pytest coverage
    - coverage run manage.py test
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  when: manual
