stages:
  - build
  - test

build-app:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/main:latest backend/
    - docker push $CI_REGISTRY_IMAGE/main:latest

services:
    - mysql:5.7

variables:
  MYSQL_DATABASE: "home_tools"
  MYSQL_ROOT_PASSWORD: "home_password"
  MYSQL_ROOT_USERNAME: "root"
  MYSQL_HOST: "mysql"

test-app:
  image: $CI_REGISTRY_IMAGE/main:latest
  stage: test
  before_script:
    - cd /app
    - python manage.py makemigrations api
    - python manage.py migrate
  script:
    - coverage run manage.py test
    - coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
